controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    position_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

position_controller:
  ros__parameters:
    joints:
      - robot/front_right_hip
      - robot/front_right_knee
      - robot/front_left_hip
      - robot/front_left_knee
      - robot/rear_right_hip
      - robot/rear_right_knee
      - robot/rear_left_hip
      - robot/rear_left_knee
