<?xml version="1.0"?>
<!--
  Go1-like simple quadruped (trunk + 4 legs, 3 DoF each) for gz-sim + ros2_control (gz_ros2_control).

  Updates per user request:
  1) Hip "joint block" is a CYLINDER mounted to the SIDE and BELOW the trunk (no overlap).
  2) Knee (thigh->shank) joint is ALSO offset to the SIDE and BELOW the thigh end, not perfectly collinear.

  Notes:
  - Cylinder axis in URDF is along +Z by default. We rotate hip cylinder so its axis aligns with +X (roll axis housing).
  - Knee lateral offset is outward (left: +Y, right: -Y).
-->
<robot name="crawler" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- ======= Parameters ======= -->

  <!-- Trunk dimensions -->
  <!-- <xacro:property name="pi" value="0.20"/> -->
  <xacro:property name="body_x" value="0.20"/>
  <xacro:property name="body_y" value="0.20"/>
  <xacro:property name="body_z" value="0.10"/>

  <!-- Leg geometry -->
  <xacro:property name="joint_len"  value="0.036"/>   <!-- hip cylinder length -->
  <xacro:property name="joint_rad"  value="0.018"/>  <!-- hip cylinder radius -->

  <xacro:property name="link_1_len" value="0.10"/>
  <xacro:property name="link_1_rad" value="0.020"/>

  <xacro:property name="link_2_len" value="0.10"/>
  <xacro:property name="link_2_rad" value="0.020"/>

  <xacro:property name="link_3_len" value="0.10"/>
  <xacro:property name="link_3_rad" value="0.020"/>

  <xacro:property name="foot_rad" value="0.025"/>

  <!-- Mounting offsets -->
    <xacro:property name="joint_clear_y" value="${joint_rad}"/>   <!-- move hip outside trunk side -->
  <xacro:property name="joint_drop_z"  value="${joint_rad}"/>   <!-- move hip below trunk -->

  <!-- Knee joint lateral offset (outward) -->
    <xacro:property name="knee_clear_y" value="0.05"/>
  <!-- Knee joint fore/aft offset (to mimic side-mounted joint brackets as in example) -->
    <xacro:property name="knee_fwd_x" value="0.02"/>

  <!-- Simple masses -->
  <xacro:property name="m_trunk" value="1.0"/>
  <xacro:property name="m_joint"   value="0.25"/>
  <xacro:property name="m_link_1" value="0.35"/>
  <xacro:property name="m_link_2" value="0.25"/>
  <xacro:property name="m_link_3" value="0.25"/>
  <xacro:property name="m_foot"  value="0.05"/>

  <!-- Convenience -->
  <xacro:macro name="inertial_box" params="m x y z">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <!-- crude diagonal inertia, good enough for sim bringup -->
      <inertia
        ixx="${m*(y*y+z*z)/12.0}"
        iyy="${m*(x*x+z*z)/12.0}"
        izz="${m*(x*x+y*y)/12.0}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="inertial_cyl" params="m r l axis">
    <!-- axis: 'z' assumes cylinder axis is z in link frame -->
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${m}"/>
      <!-- Approx inertia for solid cylinder along z -->
      <inertia
        ixx="${m*(3*r*r + l*l)/12.0}"
        iyy="${m*(3*r*r + l*l)/12.0}"
        izz="${m*(r*r)/2.0}"
        ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </xacro:macro>

  <!-- ======= Base / Trunk ======= -->
  <link name="base_link"/>

  <link name="trunk">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="${body_x} ${body_y} ${body_z}"/></geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry><box size="${body_x} ${body_y} ${body_z}"/></geometry>
    </collision>
    <xacro:inertial_box m="${m_trunk}" x="${body_x}" y="${body_y}" z="${body_z}"/>
  </link>

  <joint name="base_to_trunk" type="fixed">
    <parent link="base_link"/>
    <child link="trunk"/>
    <origin xyz="0 0 0.30" rpy="0 0 0"/>
  </joint>


  <gazebo reference="trunk">
    <material>Gazebo/Yellow</material> 
      <mu1>150.01</mu1>
      <mu2>150.01</mu2>
  </gazebo>

  <!-- ======= Leg macro ======= -->
  <!-- side = 'l' or 'r' determines y sign; end = 'f' or 'h' determines x sign -->
  <xacro:macro name="leg3dof" params="leg xsign ysign">
    <!-- Mount point at trunk corner, then moved OUTWARD (y) and DOWN (z) -->
    <xacro:property name="x_mount" value="${xsign * body_x/2.0}"/>
    <xacro:property name="y_mount" value="${ysign * (body_y/2.0 + joint_clear_y)}"/>
    <xacro:property name="z_mount" value="${-(body_z/2.0 - joint_drop_z)}"/>

    <!-- Hip link: cylinder "housing" -->
    <link name="${leg}_joint_cyl_1">
      <visual>
        <!-- rotate cylinder so its axis aligns with +X -->
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${-xsign*ysign*pi/4}"/>
        <geometry><cylinder radius="${joint_rad}" length="${joint_len}"/></geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${-xsign*ysign*pi/4}"/>
        <geometry><cylinder radius="${joint_rad}" length="${joint_len}"/></geometry>
      </collision>
      <!-- inertia computed in link frame (cyl along z), but we're rotating visual/collision only; good enough -->
      <xacro:inertial_cyl m="${m_joint}" r="${joint_rad}" l="${joint_len}" axis="z"/>
    </link>

    <joint name="${leg}_joint_1" type="revolute">
      <parent link="trunk"/>
      <child link="${leg}_joint_cyl_1"/>
      <origin xyz="${x_mount} ${y_mount} ${z_mount}" rpy="0 0 0"/>
      <!-- ab/ad around X -->
      <axis xyz="${ysign} ${-xsign} 0"/>
      <limit lower="-1.3" upper="1.3" effort="50" velocity="6.0"/>
      <dynamics damping="0.5" friction="0.01"/>
    </joint>


    <!-- Thigh Link: cylinder -->
    <link name="${leg}_link_1">
      <visual>
        <!-- rotate cylinder so its axis aligns with +X -->
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder radius="${link_1_rad}" length="${link_1_len}"/></geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder radius="${link_1_rad}" length="${link_1_len}"/></geometry>
      </collision>
      <!-- inertia computed in link frame (cyl along z), but we're rotating visual/collision only; good enough -->
      <xacro:inertial_cyl m="${m_link_1}" r="${link_1_rad}" l="${link_1_len}" axis="z"/>
    </link>

    <joint name="${leg}_joint_1_link_1" type="fixed">
      <parent link="${leg}_joint_cyl_1"/>
      <child link="${leg}_link_1"/>
      <origin xyz="0 0 ${-joint_drop_z - (link_1_len/2.0)}" rpy="0 0 0"/>
    </joint>


    <!-- Hip pitch: cylinder "housing" -->
    <link name="${leg}_joint_cyl_2">
      <visual>
        <!-- rotate cylinder so its axis aligns with +X -->
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${-xsign*ysign*pi/4}"/>
        <geometry><cylinder radius="${joint_rad}" length="${joint_len}"/></geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${-xsign*ysign*pi/4}"/>
        <geometry><cylinder radius="${joint_rad}" length="${joint_len}"/></geometry>
      </collision>
      <!-- inertia computed in link frame (cyl along z), but we're rotating visual/collision only; good enough -->
      <xacro:inertial_cyl m="${m_joint}" r="${joint_rad}" l="${joint_len}" axis="z"/>
    </link>

    <joint name="${leg}_joint_2" type="revolute">
      <parent link="${leg}_link_1"/>
      <child link="${leg}_joint_cyl_2"/>
      <origin xyz="0.0 0.0 ${-joint_drop_z - (link_1_len/2.0)}" rpy="0 0 0"/>
      <!-- ab/ad around X -->
      <axis xyz="${ysign} ${-xsign} 0"/>
      <limit lower="-1.7" upper="1.7" effort="50" velocity="6.0"/>
      <dynamics damping="0.5" friction="0.01"/>
    </joint>

    <!-- Thigh Link: cylinder -->
    <link name="${leg}_link_2">
      <visual>
        <!-- rotate cylinder so its axis aligns with +X -->
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder radius="${link_2_rad}" length="${link_2_len}"/></geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder radius="${link_2_rad}" length="${link_2_len}"/></geometry>
      </collision>
      <!-- inertia computed in link frame (cyl along z), but we're rotating visual/collision only; good enough -->
      <xacro:inertial_cyl m="${m_link_2}" r="${link_2_rad}" l="${link_2_len}" axis="z"/>
    </link>

    <joint name="${leg}_joint_2_link_2" type="fixed">
      <parent link="${leg}_joint_cyl_2"/>
      <child link="${leg}_link_2"/>
      <origin xyz="0 0 ${-joint_drop_z - (link_2_len/2.0)}" rpy="0 0 0"/>
    </joint>

    <!-- Knee pitch: cylinder "housing" -->
    <link name="${leg}_joint_cyl_3">
      <visual>
        <!-- rotate cylinder so its axis aligns with +X -->
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${-xsign*ysign*pi/4}"/>
        <geometry><cylinder radius="${joint_rad}" length="${joint_len}"/></geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 ${pi/2} ${-xsign*ysign*pi/4}"/>
        <geometry><cylinder radius="${joint_rad}" length="${joint_len}"/></geometry>
      </collision>
      <!-- inertia computed in link frame (cyl along z), but we're rotating visual/collision only; good enough -->
      <xacro:inertial_cyl m="${m_joint}" r="${joint_rad}" l="${joint_len}" axis="z"/>
    </link>

    <joint name="${leg}_joint_3" type="revolute">
      <parent link="${leg}_link_2"/>
      <child link="${leg}_joint_cyl_3"/>
      <origin xyz="0.0 0.0 ${-joint_drop_z - (link_1_len/2.0)}" rpy="0 0 0"/>
      <!-- ab/ad around X -->
      <axis xyz="${ysign} ${-xsign} 0"/>
      <limit lower="-1.7" upper="1.7" effort="50" velocity="6.0"/>
      <dynamics damping="0.5" friction="0.01"/>
    </joint>


    <!-- Thigh Link: cylinder -->
    <link name="${leg}_link_3">
      <visual>
        <!-- rotate cylinder so its axis aligns with +X -->
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder radius="${link_3_rad}" length="${link_3_len}"/></geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><cylinder radius="${link_3_rad}" length="${link_3_len}"/></geometry>
      </collision>
      <!-- inertia computed in link frame (cyl along z), but we're rotating visual/collision only; good enough -->
      <xacro:inertial_cyl m="${m_link_3}" r="${link_3_rad}" l="${link_3_len}" axis="z"/>
    </link>

    <joint name="${leg}_joint_3_link_3" type="fixed">
      <parent link="${leg}_joint_cyl_3"/>
      <child link="${leg}_link_3"/>
      <origin xyz="0 0 ${-joint_drop_z - (link_2_len/2.0)}" rpy="0 0 0"/>
    </joint>


    <!-- Foot -->
    <link name="${leg}_foot">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><sphere radius="${foot_rad}"/></geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><sphere radius="${foot_rad}"/></geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${m_foot}"/>
        <inertia ixx="1e-5" iyy="1e-5" izz="1e-5" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <joint name="${leg}_ankle_fixed" type="fixed">
      <parent link="${leg}_link_3"/>
      <child link="${leg}_foot"/>
      <origin xyz="0 0 ${-link_3_len/2}" rpy="0 0 0"/>
    </joint>



    <gazebo reference="${leg}_joint_cyl_1">
      <material>Gazebo/Blue</material> 
        <mu1>10.01</mu1>
        <mu2>1.01</mu2>
    </gazebo>

    <gazebo reference="${leg}_joint_cyl_2">
      <material>Gazebo/Green</material> 
        <mu1>10.01</mu1>
        <mu2>1.01</mu2>
    </gazebo>
    <gazebo reference="${leg}_joint_cyl_3">
      <material>Gazebo/Red</material> 
        <mu1>10.01</mu1>
        <mu2>1.01</mu2>
    </gazebo>
    <gazebo reference="${leg}_link_1">
      <material>Gazebo/Grey</material> 
        <mu1>10.01</mu1>
        <mu2>1.01</mu2>
    </gazebo>
    <gazebo reference="${leg}_link_2">
      <material>Gazebo/Grey</material> 
        <mu1>10.01</mu1>
        <mu2>1.01</mu2>
    </gazebo>
    <gazebo reference="${leg}_link_3">
      <material>Gazebo/Grey</material> 
        <mu1>10.01</mu1>
        <mu2>1.01</mu2>
    </gazebo>
    <gazebo reference="${leg}_foot">
      <material>Gazebo/Orange</material> 
        <mu1>10.01</mu1>
        <mu2>1.01</mu2>
    </gazebo>
  </xacro:macro>

  <!-- 4 legs -->
  <xacro:leg3dof leg="lf" xsign="1"  ysign="1"/>
  <xacro:leg3dof leg="rf" xsign="1"  ysign="-1"/>
  <xacro:leg3dof leg="lh" xsign="-1" ysign="1"/>
  <xacro:leg3dof leg="rh" xsign="-1" ysign="-1"/>

  <!-- ======= ros2_control ======= -->
  <ros2_control name="gz_sim_system" type="system">
    <hardware>
      <plugin>gz_ros2_control/GazeboSimSystem</plugin>
    </hardware>

    <!-- Declare command/state interfaces for each actuated joint -->
    <joint name="lf_joint_1">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="rf_joint_1">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="lh_joint_1">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="rh_joint_1">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint> 

    <joint name="lf_joint_2">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="rf_joint_2">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="lh_joint_2">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="rh_joint_2">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="lf_joint_3">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="rf_joint_3">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="lh_joint_3">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>

    <joint name="rh_joint_3">
      <command_interface name="position"/>
      <state_interface name="position"/>
      <state_interface name="velocity"/>
    </joint>
  </ros2_control>

  <!-- ======= gz-sim plugin (NOT Gazebo Classic) ======= -->
  <gazebo>
    <plugin filename="libgz_ros2_control-system.so"
            name="gz_ros2_control::GazeboSimROS2ControlPlugin">
      <parameters>/ros_ws/src/biorobotics_tutorial/models/config/crawler_quadruped_config.yaml</parameters>
    </plugin>
  </gazebo>

</robot>